# Generated by Django 3.0.3 on 2020-02-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_sequence_number', models.SmallIntegerField()),
                ('value', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Risposta',
                'verbose_name_plural': 'Risposte',
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('relationship_with_patient', models.CharField(max_length=200)),
                ('number_of_sons', models.SmallIntegerField(blank=True, null=True)),
                ('cohabitant', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Caregiver',
                'verbose_name_plural': 'Caregivers',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('recovery_date', models.DateTimeField(blank=True, null=True)),
                ('transplant_date', models.DateTimeField(blank=True, null=True)),
                ('resignation_date', models.DateTimeField(blank=True, null=True)),
                ('transplant_type', models.CharField(max_length=50)),
                ('number_of_sons', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paziente',
                'verbose_name_plural': 'Pazienti',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('value', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tipo di Domanda',
                'verbose_name_plural': 'Tipo di Domande',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id_survey', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('patient_survey', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Questionario',
                'verbose_name_plural': 'Questionari',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_sequence_number', models.SmallIntegerField()),
                ('content', models.CharField(max_length=1000)),
                ('id_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.Survey')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.QuestionType')),
            ],
            options={
                'verbose_name': 'Domanda',
                'verbose_name_plural': 'Domande',
            },
        ),
        migrations.CreateModel(
            name='Patient_Survey_Question_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('id_answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.Answer')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_answers', to='surveys.Patient')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.Question')),
                ('id_survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.Survey')),
            ],
            options={
                'verbose_name': 'Riposta Paziente',
                'verbose_name_plural': 'Risposte Pazienti',
            },
        ),
        migrations.CreateModel(
            name='Caregiver_Survey_Question_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('id_answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.Answer')),
                ('id_caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_answers', to='surveys.Caregiver')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.Question')),
                ('id_survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.Survey')),
            ],
            options={
                'verbose_name': 'Riposta Caregiver',
                'verbose_name_plural': 'Risposte Caregivers',
            },
        ),
        migrations.AddField(
            model_name='caregiver',
            name='id_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Patient'),
        ),
        migrations.AddField(
            model_name='answer',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.Question'),
        ),
    ]
