# Generated by Django 3.0.3 on 2020-02-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20200213_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='id_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='caregiver',
            old_name='id_patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='caregiver_survey_question_answer',
            old_name='id_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='caregiver_survey_question_answer',
            old_name='id_caregiver',
            new_name='caregiver',
        ),
        migrations.RenameField(
            model_name='caregiver_survey_question_answer',
            old_name='id_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='caregiver_survey_question_answer',
            old_name='id_survey',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='patient_survey_question_answer',
            old_name='id_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='patient_survey_question_answer',
            old_name='id_patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='patient_survey_question_answer',
            old_name='id_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='patient_survey_question_answer',
            old_name='id_survey',
            new_name='survey',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='id_survey',
            new_name='survey',
        ),
    ]
