# Generated by Django 3.0.3 on 2020-02-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20200213_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='id_survey',
            new_name='name',
        ),
    ]
