# Generated by Django 3.0.3 on 2020-02-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20200213_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question', 'answer_sequence_number'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['survey', 'question_sequence_number'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
