# Generated by Django 3.0.3 on 2020-02-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20200213_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question', 'answer_sequence_number', 'answer_subsequence_number'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_subsequence_number',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
