# Generated by Django 3.0.3 on 2020-02-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20200214_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='istructions_in_compound_questions',
            field=models.BooleanField(default=False),
        ),
    ]
