# Generated by Django 3.0.3 on 2020-02-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_question_istructions_in_compound_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='istructions_in_compound_questions',
        ),
    ]
