# Generated by Django 3.0.3 on 2020-02-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_remove_question_istructions_in_compound_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderType',
            fields=[
                ('value', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Type Of Gender',
                'verbose_name_plural': 'Types Of Gender',
            },
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.GenderType'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='surveys.GenderType'),
        ),
    ]
