# Generated by Django 3.0.3 on 2020-02-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_auto_20200214_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver_survey_question_answer',
            name='date',
            field=models.DateField(),
        ),
    ]
