# Generated by Django 3.0.3 on 2020-02-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_auto_20200218_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_survey_question_answer',
            name='date',
            field=models.DateField(),
        ),
    ]
